name: agrilink
description: "Agrilink Mobile - Final Year Project Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI
  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.9.2
  socket_io_client: ^2.0.0
  url_launcher: ^6.3.2

  # Local Storage
  shared_preferences: ^2.5.4
  path_provider: ^2.1.1

  # Dependency Injection
  get_it: ^9.2.1

  # State Management
  flutter_bloc: ^9.1.1

  # Navigation
  go_router: ^17.1.0

  # Logging
  logger: ^2.0.2

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0

  # Media
  image_picker: ^1.1.0

  # WebView
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.0

  # Functional / Utils
  dartz: ^0.10.1
  equatable: ^2.0.5
  sms_autofill: ^2.4.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  
  # Testing
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  
  # Code Generation
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"