name: agrilink
description: "Agrilink Mobile - Final Year Project Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  shared_preferences: ^2.5.4
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  go_router: ^17.1.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"